---
version: '3'
# Example based on https://github.com/saubury/stream-smarts

services:
  mysql:
    image: debezium/example-mysql:${DEBEZIUM_VERSION}
    container_name: mysql
    ports:
     - 3306:3306
    environment:
     - MYSQL_ROOT_PASSWORD=debezium
     - MYSQL_USER=mysqluser
     - MYSQL_PASSWORD=mysqlpw
    volumes:
     - ./sql/mysql-rosetta-setup.sql:/mysql-rosetta-setup.sql

