version: '3.5'
services:  
  database:
    image: image
    container_name: database
    restart: always
    # Descomentar para dejar la base de datos como persistente
    volumes:
     - mysql_data:/var/lib/mysql/
    environment:
      MYSQL_DATABASE: 'rosetta'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'demo'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'demo'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'demo'
      LC_ALL: en_US.UTF-8
      LANG: en_US.UTF-8
      LANGUAGE: en_US.UTF-8
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    networks:
      - default_sg
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
networks:
  default_sg:
    external: true
volumes:
  mysql_data:
    driver: local  